### ISSUE TITLE
merge chinese and global branches

### ISSUE THREAD

**Issue by ATF-zero** [Akebi-Group/Akebi-GC#271]
merge chinese and global branches,
provide two injection methods during injection, and the process name is obtained to determine which injection method to use

**Comment by bo171** [comment]
现在可以这样了吗，会方便很多

**Comment by milkboy77** [comment]
I think the reason for this is to prevent ake source code from being sold at a high price.
We may have to wait for the development team to update.

**Comment by milkboy77** [comment]
I am very disgusted with those who make small profits by borrowing the fruits of others' labor.

**Comment by nuyizhilu** [comment]
> I am very disgusted with those who make small profits by borrowing the fruits of others' labor.
In fact, it sells for a good price on Taobao in China, about 20 RMB a day

**Comment by LokeYourLord** [comment]
In my opinion, all this will do is get this GitHub project shutdown/detected faster, so I personally am against it since I like being able to access the code and work with it myself, for education and to see how I can maybe contribute myself in the future.

But ultimately I'm not the one calling the shots here, it would just be a shame if this project were to shutdown.

**Comment by Taiga74164** [comment]
CN build is now in [Actions](https://github.com/Akebi-Group/Akebi-GC/actions) .. I still hope in the future they don't use different offset for CN and Global
