### ISSUE TITLE
Custom character upload into Genshin

### ISSUE THREAD

**Issue by Fractune** [Akebi-Group/Akebi-GC#29]
Is something like this possible to make? Character to be from blender **or** the format that genshin uses for their characters

![MG_1647640592063](https://user-images.githubusercontent.com/74881934/169720741-a56ed6db-c8f5-453f-9264-383cc08713a4.jpeg)

**Comment by Emilia33** [comment]
isn't this easily bannable?

**Comment by Taiga74164** [comment]
you can do this using [MelonLoader](https://github.com/LavaGang/MelonLoader). you can download the custom version for genshin in my [site](https://melon.taiga.gg/). then use [ModelChanger](https://github.com/portra400nc/ModelChanger) by @portra400nc

**Comment by LokeYourLord** [comment]
> you can do this using [MelonLoader](https://github.com/LavaGang/MelonLoader). you can download the custom version for genshin in my [site](https://melon.taiga.gg/). then use [ModelChanger](https://github.com/portra400nc/ModelChanger) by @portra400nc . you can dm me in discord if youre interested in the modding server

I suppose you could post your Discord link here if you want (I assume you share models there).

**Comment by Fractune** [comment]
Can the character changer be integrated into this tool? with a list of options for the character available 🙏🏼 

Also simple question, can others see it? (Is it serversided)

**Comment by LokeYourLord** [comment]
> @Taiga74164 Simple question, can others see it? (Is it serversided)

That's such a stupid question though because obviously it isn't server sided. If it was, you'd get banned in no time. Also, how would it be server sided when you are modifying your client only (the tool/menus never "hack" or modify the server in any capacity, as they also are incapable of doing so). That is such a simple thing to answer for yourself...

So no, others cannot see it. Aside from what I just said and the, in my opinion, obvious aspect to why it wouldn't and couldn't be, it would also require that when you change your character, that the other person either "streams" or downloads the data from your system (because how else would they see that character model without having the textures on their system locally, that is why you download games, because all that is actually being "streamed" between you and any server is just the movement data and some other, easy to transfer information, never files or information as big as textures), enabling P2P or any other function of sharing textures (because again, they obviously won't be changed server side, that'd be so suspicious as all fucking hell that I don't know why you asked such a question), and thus leading to the possibility of sharing exploits or worse, data theft or more.

I am kinda surprised you know how to use GitHub, but then go on to ask one of the most obvious, and dumbest questions of all time that would've had an answer had you for about 2 seconds thought about how the Internet (and data transfer) works.

**Comment by Fractune** [comment]
> I am kinda surprised you know how to use GitHub, but then go on to ask one of the most obvious, and dumbest questions of all time that would've had an answer had you for about 2 seconds thought about how the Internet (and data transfer) works.

Hey hey, I never used melonloader before. I only asked a simple question, no needed to be that much of a bone

**Comment by LokeYourLord** [comment]
> > I am kinda surprised you know how to use GitHub, but then go on to ask one of the most obvious, and dumbest questions of all time that would've had an answer had you for about 2 seconds thought about how the Internet (and data transfer) works.
> 
> Hey hey, I never used melonloader before. I only asked a simple question, no needed to be that much of a bone

Read all of what I just said. I didn't mention anything about you using local resources. You asked if "others" can see it, but this has never been the case in ANY game that you can mod, ever. Like ever, period. It's not just about "MelonLoader" so to speak, it's about modding or the knowledge of how games/the Internet works.

**Comment by Taiga74164** [comment]
> > you can do this using [MelonLoader](https://github.com/LavaGang/MelonLoader). you can download the custom version for genshin in my [site](https://melon.taiga.gg/). then use [ModelChanger](https://github.com/portra400nc/ModelChanger) by @portra400nc . you can dm me in discord if youre interested in the modding server
> 
> I suppose you could post your Discord link here if you want (I assume you share models there).

https://discord.gg/DEqnXaN2
will delete in 5mins

**Comment by Fractune** [comment]
I already read that part. I understand but still no need to be that much of a bone...

**Comment by LokeYourLord** [comment]
> I already read that part. I understand but still no need to be that much of a bone...

Not everything in life has to be told in a coddling manner. Now you learned from that and won't make the mistake again in the future. This generation of coddling people, I swear... I miss the MW2 era 😂

**Comment by Fractune** [comment]
> Not everything in life has to be told in a coddling manner. Now you learned from that and won't make the mistake again in the future. This generation of coddling people, I swear... I miss the MW2 era 😂

Huh? All I did was to ask a simple question, how did I do a mistake by doing so. You got mad for no pure reason

**Comment by LokeYourLord** [comment]
> > Not everything in life has to be told in a coddling manner. Now you learned from that and won't make the mistake again in the future. This generation of coddling people, I swear... I miss the MW2 era 😂
> 
> Huh? All I did was to ask a simple question, how did I do a mistake by doing so. You got mad for no pure reason

You could've asked a meaningful question, because this isn't Quora. This is GitHub, people here hold a tad more knowledge than just being able to breathe. You could've Googled it as well, because that question is actually being brought up fairly often across plenty of games with "do people see what I do when I mod x locally?", and the answer being always no. Mad indeed, because sometimes some things are such a waste of time and are being asked so often that I can't help but get sick of reading such stupid. Because do you really think this alone ticks me off? No obviously it wouldn't, but it's the same questions for all games and development everywhere every time, and that's why I got mad because people like you cannot bother to Google for 10 seconds or use that meat ball you have in-between your skull. You have your answer now.

**Comment by Fractune** [comment]
That's true. I could have googled something I literally did yesterday but I didn't find any answers. Probably because I searched for the wrong thing the entire time. It is exactly why I asked this question here, thus if you consider helping someone "a waste of time" then what are you literally doing in the "issues" section? that's literally harsh.

**Comment by LokeYourLord** [comment]
I mean you're not wrong with saying what you are, but there's gotta be a limit to letting stuff like that slide if you know what I mean. You gotta hang someone out for drying once in a while so the collective learns from it 😂 Anyways, if you want good models to use, take a look at some Unity Model hubs via Google, or games that use Unity as well that provide character mods (Dyson Sphere Program is a good example, it has mods and Unity Character mods too).

**Comment by Fractune** [comment]
>  take a look at some Unity Model hubs via Google, or games that use Unity as well that provide character mods (Dyson Sphere Program is a good example, it has mods and Unity Character mods too).

I was planning to do that from the beginning, though I gotta search up a guide on how to install this custom "melon loader" that Taiga spoke of.

**Comment by LokeYourLord** [comment]
If you need another game that is also Unity and provides character models, check out Risk of Rain 2's mod hub: https://thunderstore.io/

**Comment by Shichiha** [comment]
You might be interested in this [here](https://github.com/lassedds/Melonloader-AnimeGaming) for the setup. note that this setup uses another project called "Grasscutter"

Also, please keep discussions short and only to contain the useful information.....

**Comment by Fractune** [comment]
> If you need another game that is also Unity and provides character models, check out Risk of Rain 2's mod hub: https://thunderstore.io/

Not really but thanks. I did download MelonLoader before for VRChat & use custom mods in it but **the problem** right now is the "custom version of genshin" to apply it

**Comment by LokeYourLord** [comment]
> > You might be interested in this [here](https://github.com/lassedds/Melonloader-AnimeGaming) for the setup. note that this setup uses another project called "Grasscutter"
> 
> I'll check that up 👍🏼 Thanks

Here is what you need specifically and first and foremost: https://github.com/Grasscutters/GrassClipper
