### ISSUE TITLE
anti-obs

### ISSUE THREAD

**Issue by fakepeek** [Akebi-Group/Akebi-GC#421]
function so that the cheat is not visible on the video/screenshots

**Comment by EchoesFromBeyond** [comment]
There is no possible way to do this that i know of without drawing the app in a separate window, which wouldn't work because then it wouldn't be inside the game frame. The best solution for you is to turn off ESP, Turn off Notifications, Turn off the Settings items that display themselves, and dont use the Map Filters. Then you have silent hidden stuff.
