### ISSUE TITLE
open reduce skill/burst cooldown，Challenge the abyss Is it safe？

### ISSUE THREAD

**Issue by lyc-ch** [Akebi-Group/Akebi-GC#604]
I am in multiplayer mode, and three accounts have been suspended for one month after using this function

**Comment by tedzify** [comment]
If you've been banned three times from using the same function, why would you think that it's safe to use on abyss? There are already a lot of warnings telling you to not cheat in abyss, as it is highly monitored. Also, playing in co-op or in your own world doesn't matter in terms of detection because, you're still playing online in their servers.

**Comment by icercat** [comment]
Well you can get banned just because anticheat is off in abyss just don't touche it when you have any thing injected

**Comment by LunarisFP** [comment]
If you got suspended from using those functions, then don't use it on spiral abyss.
I suggest you make a 'legit' config. Don't spam your skills etc.
Just to make it clear, spiral abyss is very dangerous due to your spiral abyss stats will be tracked via hoyolab, they can ban you manually if they notice anything abnormal (ex. 12-3 Spiral Abyss with highest damage being lower than 10k)
Just don't play spiral abyss if u value your account

**Comment by ClickClack7531** [comment]
> If you've been banned three times from using the same function, why would you think that it's safe to use on abyss? There are already a lot of warnings telling you to not cheat in abyss, as it is highly monitored. Also, playing in co-op or in your own world doesn't matter in terms of detection because, you're still playing online in their servers.

Yknow, It just shows how money hungry mihoyo is. There's no reason to heavily monitor Spiral Abyss. Genshin is basically a single player game. Mihoyo wants players to have fun only if they are giving mihoyo money.
