### ISSUE TITLE
[BUG] Akebi breaks window after opening f1 gui

### ISSUE THREAD

**Issue by ClickClack7531** [Akebi-Group/Akebi-GC#612]
For some reason, even time I open the Akebi gui with [f1], the Genshin window becomes frozen and borderless after a few seconds and I have to then restart.
![{0DEC6E7D-521F-4C48-8042-48CCA33DC9F6}](https://user-images.githubusercontent.com/93358773/188229919-420842ea-e129-4fd6-93b3-3e8895e7e838.png) (The Window is borderless)

No Idea what's causing this. I tried downloading the latest release and the latest patch, tried both, and my problem wasnt fixed. What to do?

**Comment by Taiga74164** [comment]
probably your PC cant handle it lol

**Comment by chirinu** [comment]
PC Issue Pc Issue 😱

**Comment by ClickClack7531** [comment]
> probably your PC cant handle it lol. i can see you have low settings and your fps is so low

Ah. I see. Well, I cant turn down the window resolution because Genshin keeps reverting it back to 1024 x 768, and I need it at 848 x 480 to run smoothly. and I cant change it because if I do the window breaks and freezes.

**Comment by qq857857** [comment]
整天BB死妈东西？




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年9月3日(星期六) 晚上8:47
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; 
主题: Re: [Akebi-Group/Akebi-GC] [BUG] Akebi breaks window after opening f1 gui (Issue #612)





  
probably your PC cant handle it lol. i can see you have low settings and your fps is so low
  
Ah. I see. Well, I cant turn down the window resolution because Genshin keeps reverting it back to 1024 x 768, and I need it at 848 x 480 to run smoothly. and I cant change it because if I do the window breaks and freezes.

**Comment by Taiga74164** [comment]
> Ah. I see. Well, I cant turn down the window resolution because Genshin keeps reverting it back to 1024 x 768, and I need it at 848 x 480 to run smoothly. and I cant change it because if I do the window breaks and freezes.

you can add launch options in cfg.ini

GenshinComnandLine =

**Comment by Shichiha** [comment]
> > Ah. I see. Well, I cant turn down the window resolution because Genshin keeps reverting it back to 1024 x 768, and I need it at 848 x 480 to run smoothly. and I cant change it because if I do the window breaks and freezes.
> 
> you can add launch options in cfg.ini
> 
> GenshinComnandLine = 
> 

nah thers a minimum resolution
