### ISSUE TITLE
Enter/Exit domain throws InteractiveMap exception

### ISSUE THREAD

**Issue by boteomap2** [Akebi-Group/Akebi-GC#65]
![image](https://user-images.githubusercontent.com/87257421/171324231-47c42ba8-f631-486a-8016-507bc8ec8568.png)

**Comment by G1DE30N** [comment]
Thats not critical, because interactive map try load set of icons from every location you go (like enkanomia) but Domains doesn't have any, thats the reason of this exception. Simply it just write "interactive map data not found". Like that.

**Comment by CallowBlack** [comment]
> Thats not critical, because interactive map try load set of icons from every location you go (like enkanomia) but Domains doesn't have any, thats the reason of this exception. Simply it just write "interactive map data not found". Like that.

You're incorrect with your conclusions about the reason of exceptions. The reason is to call unity function for the object, when minimap object only initializing or something. But surely not in any icons. Also, it can be one of reasons for #15 (but it only assumption)
https://github.com/Akebi-Group/Akebi-GC/blob/e8f97ef3a57c42c636ad3172bf2759aa99075f69/cheat-library/src/user/cheat/imap/InteractiveMap.cpp#L1345
